// CSE 450 — Design & Analysis of Algorithms
// Course data file for the Study Tool
// To update: edit this file and re-import into index.html

const CSE450_DATA = {
    code: "CSE 450",
    name: "Design & Analysis of Algorithms",
    prof: "Prof. Daymude",
    color: "#93c5fd",
    storagePrefix: "cse450_study_",
    modules: [
  {
    id: "m1", label: "Module 1", subtitle: "Stable Matching", color: "#6ee7b7",
    flashcards: [
      { q: 'What is a problem (in the context of this course)?', a: 'The "nail" — a formal specification of inputs and desired outputs. It defines what you want to solve, not how.' },
      { q: 'What is an algorithm?', a: 'The "hammer" — a step-by-step procedure that solves a problem. It defines how to solve it.' },
      { q: 'What does it mean to analyze an algorithm?', a: 'Proving it is correct (produces the right output for all inputs) and determining its efficiency (time and space complexity).' },
      { q: 'What is a matching?', a: 'A 1:1 assignment between two sets — each element is paired with at most one element from the other set.' },
      { q: 'What is a perfect matching?', a: 'A matching where every element in both sets A and B is matched to exactly one partner. No one is left unmatched.' },
      { q: 'What is an unstable pair (blocking pair)?', a: "A pair (a, b') where a prefers b' over their current partner AND b' prefers a over their current partner. Both sides must mutually prefer each other." },
      { q: 'What is a stable matching?', a: 'A perfect matching with no unstable pairs.' },
      { q: 'What is the formal definition of the Stable-Matching problem?', a: 'Input: sets A = {a\u2081,...,a\u2099} and B = {b\u2081,...,b\u2099} with strictly-ordered preference rankings for each element. Goal: find a perfect, stable matching between A and B.' },
      { q: 'What is the Gale-Shapley algorithm also called?', a: 'The "propose-and-reject" algorithm or the "deferred acceptance" algorithm.' },
      { q: 'Describe the Gale-Shapley algorithm in plain English.', a: "While there's an unmatched proposer who hasn't proposed to everyone: that proposer proposes to their top remaining choice. If the acceptor is unmatched, they accept. If matched, they accept only if they prefer the new proposer over their current partner (trading up), otherwise they reject." },
      { q: 'In Gale-Shapley, who proposes and who accepts/rejects?', a: 'Elements in A propose. Elements in B accept or reject. B never proposes.' },
      { q: 'What is the "Offer Order" observation?', a: 'Elements in A make offers to elements in B in decreasing order of preference. They always propose to their most-preferred remaining option.' },
      { q: 'What is the "Trading Up" observation?', a: 'Once an element in B accepts an offer, it never becomes unmatched again. It can only swap to a higher-preference partner.' },
      { q: 'Can an element in A propose to the same element in B more than once?', a: 'No. Each a \u2208 A proposes to each b \u2208 B at most once. The algorithm always moves to the next person on the list.' },
      { q: 'What three things must be shown to prove Gale-Shapley is correct?', a: '(1) Termination — the algorithm eventually stops. (2) Perfect matching — everyone is matched. (3) Stability — no unstable pairs exist.' },
      { q: 'How is termination proved?', a: 'Each while loop iteration uses a unique (a, b) proposal. There are at most n \u00d7 n = n\u00b2 possible proposals, so the algorithm must terminate in at most n\u00b2 iterations.' },
      { q: 'How is perfect matching proved?', a: "By contradiction. Suppose some a \u2208 A is unmatched at termination. Then some b \u2208 B must also be unmatched. By Trading Up, b is only unmatched if no one ever proposed to b. But for the algorithm to terminate, a must have proposed to everyone, including b. Contradiction." },
      { q: 'How is stability proved? (Case 1)', a: "Suppose (a, b) and (a', b') are in the matching and a prefers b' over b. Case 1: a never proposed to b'. Since a proposed to b, and proposals go in decreasing preference order, a must prefer b over b'. Contradiction." },
      { q: 'How is stability proved? (Case 2)', a: "Case 2: a did propose to b'. Since a ended up with b instead, b' must have either rejected a or accepted then traded up. By Trading Up, b' prefers a' (her final partner) over a. Contradiction." },
      { q: 'What is the runtime of the na\u00efve Gale-Shapley implementation?', a: 'O(n\u00b3). At most n\u00b2 iterations, each taking O(n) to scan for an unmatched proposer, find next proposal target, and check acceptor\'s preferences.' },
      { q: 'What is the runtime of the efficient Gale-Shapley implementation?', a: 'O(n\u00b2). At most n\u00b2 iterations, each taking O(1) using proper data structures.' },
      { q: 'What is the space complexity of efficient Gale-Shapley?', a: 'O(n\u00b2) — dominated by the preference arrays.' },
      { q: 'What data structures does the efficient implementation use?', a: '(1) Queue Q of unmatched elements in A. (2) Matching variables m(a\u1d62) and m(b\u1d62). (3) Offer counters c(a\u1d62) tracking how many proposals a\u1d62 has made. (4) Preference arrays p(a\u1d62) in preference order and inverse arrays p\u207b\u00b9(b\u1d62) in element order for O(1) comparison.' },
      { q: 'What does the inverse preference array p\u207b\u00b9(b\u1d62) do?', a: "It stores b\u1d62's preferences in element order (not rank order), so you can compare two proposers in O(1). Instead of scanning b's whole list, you just look up p\u207b\u00b9(b\u1d62)[a] and p\u207b\u00b9(b\u1d62)[a'] and compare." },
      { q: "Why can't we avoid the n\u00b2 loop iterations?", a: 'Because in the worst case, every proposer may need to propose to many acceptors before finding a match. The n\u00b2 iterations are inherent to the problem. We can only optimize the cost per iteration.' },
      { q: 'What are the five representative problems and their design paradigms?', a: 'Interval-Scheduling \u2192 Greedy. Weighted-Interval-Scheduling \u2192 Dynamic Programming. Bipartite-Matching \u2192 Network Flows. Maximum-Independent-Set \u2192 Randomized & Approximation. Competitive-Facility-Location \u2192 Heuristics.' },
      { q: 'What are the time complexities of the five representative problems?', a: 'Interval-Scheduling: O(n log n). Weighted-Interval-Scheduling: O(n log n). Bipartite-Matching: O(mn). Maximum-Independent-Set: NP-complete. Competitive-Facility-Location: PSPACE-complete.' },
      { q: 'What is the unifying theme of the five representative problems?', a: 'They are all variations on independent sets — selecting items subject to conflict constraints (non-overlapping intervals, non-adjacent nodes, non-sharing edges, etc.).' },
      { q: 'What is the Interval-Scheduling problem?', a: 'Input: n jobs with start and end times. Goal: find a maximum cardinality subset of non-overlapping jobs.' },
      { q: 'What is Weighted-Interval-Scheduling?', a: 'Input: n jobs with start times, end times, and weights. Goal: find a maximum weight subset of non-overlapping jobs.' },
      { q: 'What is the Bipartite-Matching problem?', a: 'Input: undirected bipartite graph with n nodes and m edges. Goal: find a maximum cardinality set of edges such that no two share an endpoint.' },
      { q: 'What is the Maximum-Independent-Set problem?', a: 'Input: undirected graph with n nodes and m edges. Goal: find a maximum cardinality set of nodes such that no two are joined by an edge.' },
      { q: "Why can't Maximum-Independent-Set be solved efficiently?", a: "It's NP-complete — no known polynomial-time algorithm exists for it." },
      { q: 'Why is Competitive-Facility-Location harder than Maximum-Independent-Set?', a: "It's PSPACE-complete (believed harder than NP-complete) because it involves a two-player game with adversarial turns, not just a single optimization." },
      { q: 'What are the four main algorithm design paradigms in CSE 450?', a: '(1) Greedy — build solutions incrementally, always taking the locally best next step. (2) Divide and Conquer — break into independent subproblems, solve, combine. (3) Dynamic Programming — break into overlapping subproblems, build up solutions. (4) Network Flows and Matchings — general graph-based approaches.' },
      { q: 'Do these paradigms always yield fast algorithms?', a: 'No. The slides state they "often — but not always" yield fast algorithms.' },
    ],
    trueFalse: [
      { s: "A stable matching is any 1:1 assignment of elements in A to elements in B with no unstable pairs.", ans: false, e: "It must also be a perfect matching \u2014 every element in A and B must be matched. A matching with no unstable pairs but unmatched elements doesn't satisfy the Stable-Matching problem definition." },
      { s: "In Gale-Shapley, elements in B (the acceptors) make offers to elements in A in decreasing order of preference.", ans: false, e: "It's the other way around. Elements in A (the proposers) make offers to elements in B in decreasing order of preference. B elements only accept or reject \u2014 they never propose." },
      { s: "The Gale-Shapley algorithm terminates in at most n\u00b2 while loop iterations.", ans: true, e: "Each iteration involves some a \u2208 A proposing to a b \u2208 B it hasn't proposed to before. There are n elements in A and n in B, so at most n \u00d7 n = n\u00b2 possible proposals." },
      { s: "Once an element in B accepts an offer in Gale-Shapley, it remains matched for the rest of the algorithm (though its partner may change).", ans: true, e: "This is the \u201cTrading Up\u201d observation. Once a b \u2208 B gets matched, it never becomes unmatched \u2014 it can only swap to a more preferred partner." },
      { s: "A na\u00efve implementation of Gale-Shapley runs in O(n\u00b2) time.", ans: false, e: "The na\u00efve implementation runs in O(n\u00b3). There are at most n\u00b2 iterations, and each takes O(n) to scan for an unmatched proposer, find the next person to propose to, and check preferences. The efficient implementation (queues, counters, inverse arrays) gets each iteration to O(1), bringing total time to O(n\u00b2)." },
      { s: "Using the L2 running example, when a\u2082 first proposes to b\u2085, b\u2085 accepts the offer because b\u2085 is unmatched.", ans: false, e: "When a\u2082 proposes to b\u2085, b\u2085 is already matched to a\u2081 (who proposed first). b\u2085 prefers a\u2081 over a\u2082, so b\u2085 rejects a\u2082." },
      { s: "In the stability proof for Gale-Shapley, if the final matching contains (a, b) and a never proposed to b', then a must prefer b over b'.", ans: true, e: "This is Case 1 of the stability proof. Since proposers propose in decreasing preference order and a ended up matched to b, if a never proposed to b', that means b' was lower on a's list than b." },
      { s: "The Interval-Scheduling problem is solved optimally using Dynamic Programming.", ans: false, e: "Interval-Scheduling (maximize number of non-overlapping jobs) is solved with a Greedy algorithm in O(n log n). It's Weighted-Interval-Scheduling that requires Dynamic Programming." },
      { s: "The Maximum-Independent-Set problem is NP-complete.", ans: true, e: "Stated directly on the Five Representative Problems summary slide. No known polynomial-time algorithm exists for it." },
      { s: "The five representative problems from L3 are all variations on the theme of independent sets.", ans: true, e: "Interval-Scheduling picks non-overlapping intervals, Bipartite-Matching picks non-sharing edges, Maximum-Independent-Set picks non-adjacent nodes, etc. They're all about selecting items subject to conflict constraints." },
      { s: "An efficient implementation of Gale-Shapley uses O(n\u00b2) space and runs in O(n\u00b2) time.", ans: true, e: "The efficient version uses a queue Q for unmatched proposers, matching variables, offer counters, preference arrays p(a\u1d62), and inverse preference arrays p\u207b\u00b9(b\u1d62). The preference arrays alone take O(n\u00b2) space. Runtime is O(n\u00b2) because each of the at most n\u00b2 iterations runs in O(1)." },
      { s: "In Gale-Shapley, an element in A can propose to the same element in B more than once.", ans: false, e: "Each proposer a \u2208 A proposes to each b \u2208 B at most once. The algorithm tracks this \u2014 a always proposes to the next person on their list they haven't proposed to yet. This is also why termination is guaranteed." },
      { s: "A perfect matching requires that every element in both A and B is matched to exactly one partner.", ans: true, e: "That's the definition. Perfect = 1:1, covering all elements on both sides. No one is left unmatched." },
      { s: "An unstable pair (a, b') exists when a prefers b' over their current partner AND b' prefers a over their current partner.", ans: true, e: "This is the definition of an unstable pair (blocking pair). Both sides must mutually prefer each other over their current assignments. If only one side prefers the switch, it's not unstable." },
      { s: "The Weighted-Interval-Scheduling problem has time complexity O(n log n) and is solved using a greedy algorithm.", ans: false, e: "While the time complexity O(n log n) is correct, it's solved using Dynamic Programming, not Greedy. The weights make a greedy approach fail \u2014 a long high-weight job might be better than several short low-weight ones." },
      { s: "Bipartite-Matching runs in O(mn) time and is solved using Network Flows.", ans: true, e: "Directly from the L3 summary table." },
      { s: "Competitive-Facility-Location is NP-complete.", ans: false, e: "It's PSPACE-complete, which is believed to be even harder than NP-complete. It's a two-player game, which adds complexity beyond standard optimization." },
      { s: "The Gale-Shapley algorithm's correctness proof requires showing three things: termination, perfect matching, and stability.", ans: true, e: "Slide 16 of L2 explicitly lists these three requirements for proving correctness." },
    ],
  },
  {
    id: "m2", label: "Module 2", subtitle: "Greedy Algorithms", color: "#93c5fd",
    flashcards: [
      { q: 'What is the Interval-Scheduling problem?', a: "Given n jobs with start times s(i) and finish times f(i), find a maximum cardinality subset J' \u2286 J such that all pairs of jobs in J' are compatible (non-overlapping)." },
      { q: 'What does "compatible" mean in Interval-Scheduling?', a: 'Two jobs i and j are compatible if their time intervals do not overlap \u2014 i.e., f(i) \u2264 s(j) or f(j) \u2264 s(i).' },
      { q: 'What are four greedy ideas for Interval-Scheduling, and which ones fail?', a: '(1) Earliest Start Time \u2014 FAILS. (2) Earliest Finish Time \u2014 WORKS. (3) Shortest Interval \u2014 FAILS. (4) Fewest Conflicts \u2014 FAILS.' },
      { q: 'Why does Earliest Start Time fail for Interval-Scheduling?', a: 'A single long job that starts earliest blocks many shorter compatible jobs.' },
      { q: 'Why does Shortest Interval fail for Interval-Scheduling?', a: 'A short job in the middle can overlap two longer non-overlapping jobs. Picking it gives 1 job instead of 2.' },
      { q: 'Why does Fewest Conflicts fail for Interval-Scheduling?', a: 'The slides show a specific instance where the job with fewest conflicts is not part of the optimal solution.' },
      { q: 'Describe the Earliest Finish Time algorithm step by step.', a: "(1) Initialize J' \u2190 \u2205. (2) Sort and relabel jobs so f(1) \u2264 f(2) \u2264 ... \u2264 f(n). (3) For each i = 1,...,n: if job i is compatible with J', add i to J'. (4) Return J'." },
      { q: 'What is the naive runtime of the Earliest Finish Time algorithm?', a: "O(n\u00b2) \u2014 sorting is O(n log n), but checking compatibility by comparing against all jobs in J' is O(n) per iteration, giving O(n\u00b2) for the loop." },
      { q: 'What is the efficient runtime of Earliest Finish Time, and what optimization achieves it?', a: "O(n log n). Store only the finish time of the last job added to J' and compare s(i) to f(last). Each check is O(1)." },
      { q: 'What proof technique is used for Earliest Finish Time correctness?', a: 'A staying ahead argument.' },
      { q: 'State the "staying ahead" lemma for Interval-Scheduling.', a: 'Let j\u2081,...,j\u2096 be the greedy jobs and o\u2081,...,o\u2097 be any optimal set, both sorted by finish time. Then for all i \u2264 k, f(j\u1d62) \u2264 f(o\u1d62). The greedy job finishes no later than the corresponding optimal job.' },
      { q: 'Prove the base case of the staying ahead lemma.', a: 'For i = 1: the greedy algorithm picks the job with the globally earliest finish time, so f(j\u2081) = min_j f(j) \u2264 f(o\u2081).' },
      { q: 'What is the key insight in the inductive step of the staying ahead lemma?', a: "By induction, f(j\u1d62\u208b\u2081) \u2264 f(o\u1d62\u208b\u2081). Since o\u1d62\u208b\u2081 and o\u1d62 are compatible, f(o\u1d62\u208b\u2081) \u2264 s(o\u1d62). Combining: f(j\u1d62\u208b\u2081) \u2264 s(o\u1d62), so o\u1d62 is compatible with j\u1d62\u208b\u2081. The algorithm chose j\u1d62 as the next compatible job with earliest finish, so f(j\u1d62) \u2264 f(o\u1d62)." },
      { q: 'State the optimality theorem for Earliest Finish Time.', a: 'The Earliest Finish Time algorithm always returns a maximum cardinality subset of mutually compatible jobs.' },
      { q: 'How does the optimality proof work (final contradiction)?', a: "Assume \u2113 > k. By the lemma, f(j\u2096) \u2264 f(o\u2096). Since o\u2096 and o\u2096\u208a\u2081 are compatible, f(o\u2096) \u2264 s(o\u2096\u208a\u2081), so f(j\u2096) \u2264 s(o\u2096\u208a\u2081). Then o\u2096\u208a\u2081 is compatible with j\u2096, meaning the algorithm wouldn't have stopped at k jobs \u2014 contradiction." },
      { q: 'Does the Earliest Finish Time algorithm ever revert a decision?', a: "No. Once a job is added to J', it is never removed." },
      { q: 'What is the Interval-Partitioning problem?', a: 'Given n jobs with start/finish times, find the smallest number of groups such that every job is assigned to a group and no two jobs in the same group overlap.' },
      { q: 'What is the depth of a set of intervals?', a: 'The largest number of intervals that simultaneously overlap at any point in time.' },
      { q: 'State the Depth Lower Bound observation.', a: 'The number of groups needed to partition J is at least the depth of J.' },
      { q: 'Describe the Earliest Start Time algorithm for Interval-Partitioning.', a: "(1) Initialize G \u2190 \u2205. (2) Sort jobs so s(1) \u2264 s(2) \u2264 ... \u2264 s(n). (3) For each i: if job i is compatible with some group g \u2208 G, add i to g; else create a new group {i}. (4) Return G." },
      { q: 'What is the naive runtime of the Earliest Start Time algorithm for Interval-Partitioning?', a: 'O(n\u00b2) \u2014 for each of n jobs, checking compatibility against all existing groups could take O(n).' },
      { q: 'What data structure makes Interval-Partitioning efficient, and what runtime does it achieve?', a: "A priority queue (min-heap) storing the finish time of the last job in each group. O(log n) checks, O(n log n) total." },
      { q: 'What proof technique is used for Interval-Partitioning correctness?', a: 'Matching lower bounds (also called "structural bound" argument).' },
      { q: 'Walk through the Interval-Partitioning correctness proof.', a: 'Let g = groups created, g* = optimal. When the g-th group was created, some job i was incompatible with all g-1 existing groups. Each of those groups has a job overlapping i. So g jobs overlap at time s(i)+\u03b5, meaning depth \u2265 g. By the lower bound, g* \u2265 depth \u2265 g, so g is minimum.' },
      { q: 'Does the Earliest Start Time algorithm always produce exactly depth(J) groups?', a: 'Yes. The proof shows the algorithm uses at most depth(J) groups, and since depth(J) is a lower bound, it achieves exactly the depth.' },
      { q: 'What is the Minimum-Lateness-Scheduling problem?', a: 'Given n jobs with processing times t(i) and deadlines d(i), and a single worker: order the jobs to minimize the maximum lateness L = max\u1d62 \u2113(i), where \u2113(i) = max{0, f(i) \u2212 d(i)}.' },
      { q: 'What is the lateness of a job?', a: "\u2113(i) = max{0, f(i) \u2212 d(i)}. It's how late the job finishes past its deadline (0 if on time or early)." },
      { q: 'What does the objective L = max\u1d62 \u2113(i) represent?', a: 'The maximum lateness across all jobs. We want the worst-case tardiness to be as small as possible.' },
      { q: 'Why does Shortest Processing Time First fail for Min-Lateness?', a: 'Counterexample: Job 1 has t=1, d=10; Job 2 has t=5, d=5. SPT schedules job 1 first \u2192 L = 1. But scheduling job 2 first \u2192 L = 0.' },
      { q: 'Why does Shortest Slack First fail?', a: 'Counterexample: Job 1 has t=1, d=2; Job 2 has t=10, d=10. Shortest slack = job 2 (slack 0), so it goes first \u2192 L = 9. But job 1 first \u2192 L = 1.' },
      { q: 'Describe the Earliest Deadline First algorithm.', a: '(1) Initialize t \u2190 0. (2) Sort jobs so d(1) \u2264 d(2) \u2264 ... \u2264 d(n). (3) For each i: assign s(i) \u2190 t, f(i) \u2190 t + t(i), update t \u2190 f(i). (4) Return all intervals.' },
      { q: 'What is the runtime of Earliest Deadline First?', a: 'O(n log n) \u2014 dominated by sorting.' },
      { q: 'What proof technique is used for Earliest Deadline First?', a: 'An exchange argument.' },
      { q: 'What is an inversion in the context of Min-Lateness?', a: 'Jobs i and j are inverted if j is scheduled before i but d(i) < d(j) \u2014 the job with the earlier deadline comes later.' },
      { q: 'State the exchange lemma for Min-Lateness.', a: 'Swapping two consecutive, inverted jobs does not increase the maximum lateness.' },
      { q: 'State the optimality theorem for Earliest Deadline First.', a: 'The Earliest Deadline First algorithm achieves minimum maximum lateness.' },
      { q: 'What is the Offline-Caching problem?', a: 'Given n distinct items, a cache of size k < n, and a sequence of m requests: find an eviction schedule that minimizes cache misses.' },
      { q: 'What is the Farthest in the Future eviction strategy?', a: 'On a cache miss, evict whichever cached item is requested farthest in the future.' },
      { q: 'What proof technique is used for Farthest in the Future?', a: 'A (somewhat subtle and complex) exchange argument via induction.' },
      { q: 'What is a reduced eviction schedule?', a: 'A schedule that only loads an item into the cache at the time that item is being requested (never loads items "early").' },
      { q: 'What is LRU eviction?', a: 'Least Recently Used: evict the item accessed longest ago. It is k-competitive.' },
      { q: 'Describe the truck loading problem (PS2 P1).', a: 'Packages arrive in order with weights. A truck holds max weight W. Load packages in order; when the next would exceed W, send the truck. Proved optimal via staying ahead.' },
      { q: 'Describe HappyScheduling (PS2 P2).', a: 'Given n jobs with processing times t\u1d62 and values v\u1d62, minimize \u03a3 v\u1d62f\u1d62. Sort jobs in decreasing order of v\u1d62/t\u1d62. Runtime: O(n log n). Proved via exchange argument.' },
      { q: 'Describe the cell tower problem (PS2 P3).', a: 'Houses at positions on a line, each tower covers distance d. GreedyTower places tower at h\u1d62 + d for each uncovered house. O(n) if pre-sorted. Proved via staying ahead.' },
      { q: 'Name the three proof techniques for greedy correctness.', a: '(1) Staying ahead, (2) Matching lower bounds, (3) Exchange arguments.' },
      { q: 'What is the general structure of a staying ahead argument?', a: "By induction, show that after each step, the greedy solution's measure is at least as good as the optimal's corresponding measure." },
      { q: 'What is the general structure of an exchange argument?', a: 'Take any optimal solution that differs from greedy. Transform it toward greedy (via local swaps) without worsening the objective. Conclude greedy is also optimal.' },
      { q: "What is the input to the Shortest-Path problem?", a: "A directed graph G = (V, E) with edge weights w : E \u2192 \u211d." },
      { q: "What version does Dijkstra's solve?", a: "Single-source Shortest-Path (from one source s to all other nodes)." },
      { q: "What is the key restriction for Dijkstra's?", a: "All edge weights must be nonnegative (w : E \u2192 \u211d\u22650)." },
      { q: "Describe the greedy idea behind Dijkstra's.", a: "Maintain a set S of explored nodes with confirmed shortest distances. At each step, add the unexplored node u with smallest tentative distance d(u), then update neighbors." },
      { q: "What is the runtime of Dijkstra's with a priority queue?", a: "O(n log n + m), where n = |V| and m = |E|." },
      { q: "What proof technique is used for Dijkstra's correctness?", a: "Induction on |S|, the number of explored nodes." },
      { q: "Why does Dijkstra's proof require nonnegative weights?", a: "The sub-path from y to v must have nonneg length. Negative edges could decrease the total, breaking the inequality chain." },
      { q: "What is a spanning tree?", a: "A subset of edges T \u2286 E such that (V, T) is connected and acyclic (includes all nodes)." },
      { q: "Describe Kruskal's algorithm.", a: "Start with T = \u2205, consider edges in ascending weight order, add each edge unless it creates a cycle." },
      { q: "Describe Prim's algorithm.", a: "Start at a root node, iteratively add the lowest-weight edge with exactly one endpoint in the current tree." },
      { q: "What is Kruskal's runtime?", a: "O(m log n) \u2014 dominated by sorting edges." },
      { q: "What is Prim's runtime?", a: "O(m log n) \u2014 n extract-min and m decrease-key operations, each O(log n)." },
      { q: "State the Cut Property.", a: "For any subset S \u2282 V, the minimum-weight edge e with exactly one endpoint in S must be in the MST." },
      { q: "State the Cycle Property.", a: "For any cycle C in G, the maximum-weight edge f in C is not in the MST." },
      { q: "How is Prim's correctness proved?", a: "At each step, S forms a cut. Prim's adds the min-weight edge crossing it. By the Cut Property, every edge Prim's adds is in the MST." },
      { q: "What is a minimum bottleneck tree?", a: "A spanning tree T' that minimizes max_{e\u2208T'} w(e), the weight of its heaviest edge." },
      { q: "Is every MST also a minimum bottleneck tree?", a: "Yes. Proved by contradiction using the Cycle Property." },
      { q: "What is the defining characteristic of a greedy algorithm?", a: 'It always takes the "locally best" next step, and once a choice is made, it\'s permanent (never backtracks).' },
      { q: "Dijkstra's vs. Kruskal's/Prim's runtime?", a: "Dijkstra's: O(n log n + m). Kruskal's and Prim's: O(m log n)." },
    ],
    trueFalse: [
      { s: "The Interval-Scheduling problem asks for the minimum number of resources needed to schedule all jobs.", ans: false, e: "That's Interval-Partitioning. Interval-Scheduling asks for a maximum cardinality subset of mutually compatible jobs." },
      { s: "The Earliest Finish Time algorithm considers jobs in ascending order of f(i) and adds each compatible job.", ans: true, e: "The algorithm sorts by finish time, iterates through, and adds each compatible job to J'." },
      { s: "The Earliest Finish Time algorithm runs in O(n\u00b2) time because it must check compatibility with all previously selected jobs.", ans: false, e: "It runs in O(n log n). The efficient implementation only checks against the last selected job, making each check O(1)." },
      { s: "The Fewest Conflicts greedy rule is optimal for Interval-Scheduling.", ans: false, e: "A specific counterexample shows Fewest Conflicts fails." },
      { s: "In the staying ahead proof, the lemma states f(j\u1d62) \u2264 f(o\u1d62) for all i \u2264 k, meaning every greedy job starts no later than the corresponding optimal job.", ans: false, e: "It's about finish times, not start times." },
      { s: "Consider jobs (start, finish): A=(0,3), B=(2,5), C=(4,7), D=(6,9), E=(8,11). EFT selects {A, C, E}.", ans: true, e: "Sort by finish: A(3), B(5), C(7), D(9), E(11). Select A. Skip B (2<3). Select C (4\u22653). Skip D (6<7). Select E (8\u22657)." },
      { s: "In the optimality proof for EFT, the contradiction arises because if optimal had more jobs, greedy would have found another compatible job.", ans: true, e: "If \u2113 > k, then f(j\u2096) \u2264 f(o\u2096) \u2264 s(o\u2096\u208a\u2081), so o\u2096\u208a\u2081 is compatible with j\u2096, contradicting that the algorithm stopped." },
      { s: "The Earliest Finish Time algorithm sometimes removes a previously selected job.", ans: false, e: "Once a job is added, it is never removed." },
      { s: "Jobs A=(0,4), B=(1,2), C=(3,5), D=(5,7). Sorted by finish time: B, A, C, D.", ans: true, e: "Finish times: B=2, A=4, C=5, D=7." },
      { s: "For the above instance, EFT selects {B, C, D}.", ans: true, e: "Select B (finish 2). Skip A (0<2). Select C (3\u22652). Select D (5\u22655). Result: {B, C, D}." },
      { s: "The depth of a set of intervals is the total number of intervals.", ans: false, e: "Depth is the maximum number of intervals overlapping at any single point in time." },
      { s: "The number of groups needed is always exactly equal to the depth.", ans: true, e: "The Earliest Start Time algorithm achieves exactly depth(J) groups." },
      { s: "The Earliest Start Time algorithm for Interval-Partitioning sorts by finish time.", ans: false, e: "It sorts by start time." },
      { s: "Interval-Partitioning achieves O(n log n) runtime by using a priority queue.", ans: true, e: "The PQ stores finish times of last jobs in each group, O(log n) per check." },
      { s: "In the Interval-Partitioning proof, when the g-th group is created, there are g mutually overlapping jobs at time s(i) + \u03b5.", ans: true, e: "Job i was incompatible with all g-1 groups, each having a running job. Including i = g overlapping jobs." },
      { s: "The Interval-Partitioning proof uses an exchange argument.", ans: false, e: "It uses a matching lower bounds argument." },
      { s: "If no two jobs overlap, Interval-Partitioning assigns all jobs to one group.", ans: true, e: "Depth = 1, so one group suffices." },
      { s: "The lateness of job i is \u2113(i) = f(i) \u2212 d(i), which can be negative.", ans: false, e: "\u2113(i) = max{0, f(i) \u2212 d(i)}. It is never negative." },
      { s: "The goal of Min-Lateness is to minimize the sum of all job latenesses.", ans: false, e: "The goal is to minimize the maximum lateness L = max\u1d62 \u2113(i), not the sum." },
      { s: "Earliest Deadline First always leaves idle time between jobs.", ans: false, e: "It schedules jobs back-to-back with no idle time." },
      { s: "There always exists an optimal schedule with no idle time between jobs.", ans: true, e: "This is the Optimal Idle observation." },
      { s: "An inversion occurs when job j is before job i but d(j) < d(i).", ans: false, e: "The definition is: j is before i but d(i) < d(j). The inequality is backwards." },
      { s: "Swapping two consecutive inverted jobs can increase the maximum lateness.", ans: false, e: "The exchange lemma proves swapping does NOT increase max lateness." },
      { s: "After swapping inverted jobs i and j, job i's lateness can only decrease.", ans: true, e: "Moving a job earlier means it finishes sooner." },
      { s: "After swapping, the new lateness of job j satisfies \u2113'(j) < \u2113(i).", ans: true, e: "Since d(i) < d(j), we get f(i) \u2212 d(j) < f(i) \u2212 d(i) = \u2113(i)." },
      { s: "The EDF correctness proof works by showing the greedy schedule has no inversions, and any optimal can be made inversion-free via swaps.", ans: true, e: "Each swap doesn't worsen the objective." },
      { s: "Shortest Processing Time First minimizes maximum lateness.", ans: false, e: "A counterexample disproves this." },
      { s: "Jobs t(1)=3,d(1)=5; t(2)=2,d(2)=8; t(3)=1,d(3)=4. EDF schedules them 3, 1, 2.", ans: true, e: "Sort by deadline: d(3)=4, d(1)=5, d(2)=8." },
      { s: "For the above, maximum lateness under EDF is 0.", ans: true, e: "All jobs finish before their deadlines." },
      { s: "If all jobs have the same deadline, any order without idle time achieves the same max lateness.", ans: true, e: "L = f(last job) \u2212 d, which is the same regardless of order." },
      { s: "In Offline-Caching, a cache miss always requires loading, but eviction only happens when cache is full.", ans: true, e: "If not full, no eviction needed." },
      { s: "Farthest in the Future evicts the most recently added item.", ans: false, e: "That's LIFO. FiF evicts the item requested farthest in the future." },
      { s: "Farthest in the Future is practical for real-world caching.", ans: false, e: "It requires knowledge of all future requests (offline)." },
      { s: "A nonreduced schedule might load items before they are requested.", ans: true, e: "That's exactly what makes it nonreduced." },
      { s: "Converting a nonreduced schedule to reduced can increase item loads.", ans: false, e: "The lemma proves it never increases loads." },
      { s: "In the FiF proof base case (i=0), no schedule has made any decisions yet.", ans: true, e: "All start with the same initial cache." },
      { s: "In Case 1 of the FiF proof (cache hit), both schedules must evict.", ans: false, e: "On a cache hit, neither evicts anything." },
      { s: "In Case 3, when S_FF evicts x and S* evicts y \u2260 x, the subcase r\u2c7c = x is impossible.", ans: true, e: "S_FF chose to evict x because x is farther in the future than y." },
      { s: "Cache = {a,b,c} (k=3), requests: d,a,b,c,a,d,b. On request for d, FiF evicts c.", ans: true, e: "Next occurrences: a at 2, b at 3, c at 4. c is farthest." },
      { s: "Cache = {a,b} (k=2), requests: a,b,c,a,b,c. First eviction on c evicts a.", ans: false, e: "Next a at position 4, next b at position 5. b is farther, so evict b." },
      { s: "LRU is the optimal strategy for Online-Caching.", ans: false, e: "LRU is k-competitive but not optimal." },
      { s: "LIFO is k-competitive for Online-Caching.", ans: false, e: "LIFO can be arbitrarily bad." },
      { s: "The truck loading greedy is optimal because it maximizes packages per truck.", ans: true, e: "Proved by staying ahead." },
      { s: "Truck loading allows reordering packages.", ans: false, e: "Packages must be shipped in arrival order." },
      { s: "HappyScheduling minimizes the maximum completion time.", ans: false, e: "It minimizes \u03a3 v\u1d62f\u1d62 \u2014 weighted sum of completion times." },
      { s: "HappyScheduling sorts in increasing order of v\u1d62/t\u1d62.", ans: false, e: "Decreasing order. High-value-per-unit-time jobs go first." },
      { s: "In HappyScheduling exchange proof, swapping only affects those two jobs' finish times.", ans: true, e: "All other jobs are unchanged." },
      { s: "In the cell tower problem, the greedy places the first tower at h\u2081.", ans: false, e: "It places it at h\u2081 + d." },
      { s: "Cell tower staying ahead shows t\u1d62 \u2265 o\u1d62 for all i.", ans: true, e: "Greedy towers are at least as far forward as optimal towers." },
      { s: "Every MST is also a minimum bottleneck tree.", ans: true, e: "Proved using the Cycle Property." },
      { s: "All greedy algorithms in this module have runtime O(n log n).", ans: true, e: "EFT, EST (Partitioning), EDF, and HappyScheduling all run in O(n log n)." },
      { s: "Exchange arguments and staying ahead arguments are interchangeable.", ans: false, e: "Different problem structures call for different techniques." },
      { s: "A greedy algorithm never reconsiders or reverts a decision.", ans: true, e: "This is a defining characteristic of greedy algorithms." },
      { s: "All four greedy algorithms (IS, IP, MLS) sort by the same criterion.", ans: false, e: "IS by finish time, IP by start time, MLS by deadline." },
      { s: "Using Earliest Start Time instead of EFT for Interval-Scheduling gives the same result.", ans: false, e: "EST is not optimal \u2014 a long early-starting job blocks shorter ones." },
      { s: "Interval-Partitioning's proof is different because it uses a lower bound rather than direct comparison.", ans: true, e: "The proof shows algorithm output matches the depth lower bound." },
      { s: "In all exchange proofs in this module, the swap is performed on OPT to make it more like greedy.", ans: true, e: "Take OPT, swap toward greedy, show objective doesn't worsen." },
      { s: "The FiF proof is more complex than Min-Lateness because it constructs a new optimal schedule at each step.", ans: true, e: "Multiple subcases and nonreduced schedule transformations are needed." },
      { s: "Dijkstra's works correctly on graphs with negative edge weights.", ans: false, e: "The correctness proof relies on nonneg weights." },
      { s: "Dijkstra's runs in O(n\u00b2 + m) without a PQ and O(n log n + m) with one.", ans: true, e: "Without PQ: O(n) per iteration. With Fibonacci heap PQ: O(log n) amortized." },
      { s: "The Cut Property refers to the min-weight edge with both endpoints in S.", ans: false, e: "It refers to the edge with exactly one endpoint in S (crossing the cut)." },
      { s: "The Cycle Property states: for any cycle C, the max-weight edge in C is not in the MST.", ans: true, e: "Proved via exchange argument." },
      { s: "Kruskal's processes edges in descending order of weight.", ans: false, e: "Ascending order. Reverse-Delete uses descending." },
      { s: "Prim's can be proven correct using only the Cut Property.", ans: true, e: "At each step, S forms a cut; Prim's adds the lightest crossing edge." },
      { s: "Kruskal's correctness uses both Cut and Cycle Properties.", ans: true, e: "Cut Property for added edges, Cycle Property for skipped edges." },
      { s: "Every minimum bottleneck tree is also an MST.", ans: false, e: "Counterexample: 4-node complete graph where min bottleneck tree has weight 14 vs MST weight 12." },
      { s: "Every MST is also a minimum bottleneck tree.", ans: true, e: "Proved by contradiction using Cycle Property." },
      { s: "GreedyTower places the first tower at the first house.", ans: false, e: "At h\u2081 + d, not h\u2081." },
      { s: "GreedyTower is proven using an exchange argument.", ans: false, e: "It uses a staying ahead argument." },
      { s: "In Prim's, the PQ key \u2113(v) represents shortest path distance from source.", ans: false, e: "That's Dijkstra's. In Prim's, \u2113(v) is the min-weight edge connecting v to S." },
      { s: "Both Kruskal's and Prim's run in O(m log n).", ans: true, e: "Kruskal's: sorting edges. Prim's: n extract-min + m decrease-key." },
      { s: "Time-Dependent Dijkstra is identical to standard Dijkstra except edge weights are replaced by query function calls.", ans: true, e: "Same greedy strategy, but uses f(e, d(u)) instead of static weights." },
      { s: "Dijkstra's proves correctness by induction on the number of edges in S.", ans: false, e: "Induction on |S|, the number of explored nodes." },
      { s: "Reverse-Delete removes an edge iff doing so would not disconnect T.", ans: true, e: "Considers edges in descending weight, removes if T stays connected." },
      { s: "In the Cut Property proof, the cycle formed by adding e must contain another crossing edge f.", ans: true, e: "The cycle must cross from S to V\\S and back." },
      { s: "Kruskal's uses a priority queue.", ans: false, e: "Kruskal's uses union-find. Prim's and Dijkstra's use PQs." },
      { s: "HappyScheduling sorts by decreasing v\u1d62/t\u1d62 and is proven via exchange argument.", ans: true, e: "Swapping consecutive inverted pairs reduces total weighted completion time." },
    ],
  },
  {
    id: "m3", label: "Module 3", subtitle: "Divide & Conquer", color: "#fca5a5",
    flashcards: [
      { q: "What are the three steps of divide and conquer?", a: "(1) Break the problem into subproblems, (2) Solve subproblems recursively, (3) Combine subsolutions." },
      { q: "What are the three methods for solving recurrences?", a: "(1) Unrolling / recursion tree, (2) Substitution (guess and verify by induction), (3) Master Method." },
      { q: "For T(n) = 2T(n/2) + O(n), what is the solution?", a: "O(n log n). Each level does O(n) work, O(log n) levels." },
      { q: "What is the general idea behind D&C speedups for multiplication?", a: "Reduce the number of recursive calls by cleverly reusing intermediate results, even with more additions." },
      { q: "Describe MergeSort's three steps.", a: "(1) Split the list into two halves. (2) Sort each half recursively. (3) Merge the two sorted halves in O(n) time." },
      { q: "What is MergeSort's recurrence and runtime?", a: "T(n) = 2T(n/2) + O(n). Runtime: O(n log n)." },
      { q: "How does the Merge subroutine work?", a: "Two pointers, one per sorted sublist. Compare front elements, append smaller. When one exhausted, append the rest. O(n) time." },
      { q: "What is the Closest-Pair-of-Points problem?", a: "Input: n distinct points in \u211d\u00b2. Goal: Find the pair minimizing Euclidean distance." },
      { q: "What is the brute-force runtime for Closest Pair?", a: "O(n\u00b2) \u2014 check all pairs." },
      { q: "What are the three steps of Closest Pair D&C?", a: "(1) Draw vertical line L splitting into halves. (2) Recurse: find \u03b4\u2097 and \u03b4\u1d63. (3) Combine: find \u03b4\u2098 in the 2\u03b4 strip. Return min(\u03b4\u2097, \u03b4\u1d63, \u03b4\u2098)." },
      { q: "What is the key idea in the Closest Pair combine step?", a: "Only check points within a 2\u03b4 strip. Sort by y, check each point against next 11. Combine is O(n)." },
      { q: "Why at most 11 points per point in the strip?", a: "Partition strip into (\u03b4/2)\u00d7(\u03b4/2) boxes. No two same-side points share a box. Only 2 rows matter \u2192 at most 11 other boxes." },
      { q: "Why does naive D&C Closest Pair run in O(n log\u00b2 n)?", a: "Sorting the strip at every recursive level: T(n) = 2T(n/2) + O(n log n) = O(n log\u00b2 n)." },
      { q: "How to improve Closest Pair to O(n log n)?", a: "Pre-sort by x and y once. Maintain sorted orders through recursion. Each level becomes O(n)." },
      { q: "What is brute-force Integer Multiplication runtime?", a: "O(n\u00b2) \u2014 the grade school method." },
      { q: "Why doesn't naive D&C help for integer multiplication?", a: "4 recursive multiplications: T(n) = 4T(n/2) + O(n) = O(n\u00b2). Same as brute force." },
      { q: "What is Karatsuba's key insight?", a: "Compute 3 multiplications instead of 4: a\u2081b\u2081, a\u2080b\u2080, and (a\u2081+a\u2080)(b\u2081+b\u2080). Cross term recovered by subtraction." },
      { q: "What is Karatsuba's recurrence and runtime?", a: "T(n) = 3T(n/2) + O(n). Runtime: O(n^(log\u2082 3)) = O(n^1.585)." },
      { q: "Who conjectured \u03a9(n\u00b2) for multiplication?", a: "Kolmogorov in 1960. Karatsuba disproved it a week later." },
      { q: "Best known integer multiplication (as of 2019)?", a: "Harvey and van der Hoeven's O(n log n)." },
      { q: "Complex multiplication with 3 real multiplications?", a: "Compute ac, bd, and (a+b)(c+d). Real part: ac\u2212bd. Imaginary: (a+b)(c+d)\u2212ac\u2212bd." },
      { q: "What is brute-force matrix multiplication runtime?", a: "O(n\u00b3)." },
      { q: "Why doesn't naive D&C help for matrix multiplication?", a: "8 recursive multiplications: T(n) = 8T(n/2) + O(n\u00b2) = O(n\u00b3). Same as brute force." },
      { q: "What is Strassen's key idea?", a: "Reduce 8 recursive multiplications to 7 using clever products P\u2081\u2013P\u2087 with additional additions." },
      { q: "What is Strassen's recurrence and runtime?", a: "T(n) = 7T(n/2) + O(n\u00b2). Runtime: O(n^(log\u2082 7)) = O(n^2.807)." },
      { q: "Current best matrix multiplication exponent?", a: "\u2248 2.371 (Vassilevska Williams et al.)." },
      { q: "Solve: T(n) = 2T(n/2) + O(n)", a: "O(n log n)." },
      { q: "Solve: T(n) = 4T(n/2) + O(n)", a: "O(n\u00b2)." },
      { q: "Solve: T(n) = 3T(n/2) + O(n)", a: "O(n^1.585)." },
      { q: "Solve: T(n) = 8T(n/2) + O(n\u00b2)", a: "O(n\u00b3)." },
      { q: "Solve: T(n) = 7T(n/2) + O(n\u00b2)", a: "O(n^2.807)." },
      { q: "Solve: T(n) = T(n/4) + T(3n/4) + O(n)", a: "O(n log n). Each level sums to O(n), depth \u0398(log n)." },
      { q: "Why is T(n) = T(\u221an) + T(n \u2212 \u221an) + O(n) NOT O(n log n)?", a: "Subproblem stays \u2265 n/2 for ~\u221an steps, giving \u03a9(n^(3/2))." },
      { q: "Median of two sorted databases in O(log n) queries?", a: "Binary search: query \u230ak/2\u230b-th element from each side, eliminate smaller side. k halves each step." },
      { q: "For which problems did naive D&C fail to improve?", a: "Integer Multiplication (4 calls \u2192 O(n\u00b2)) and Matrix Multiplication (8 calls \u2192 O(n\u00b3))." },
    ],
    trueFalse: [
      { s: "MergeSort has a worst-case runtime of O(n\u00b2).", ans: false, e: "MergeSort always runs in O(n log n) regardless of input." },
      { s: "The Merge subroutine runs in O(n) time.", ans: true, e: "Each element is compared and placed exactly once." },
      { s: "MergeSort splits into two equal subproblems and does O(n) combine work.", ans: true, e: "Splits into ~n/2 halves, merges in O(n)." },
      { s: "Brute-force Closest Pair runs in O(n log n).", ans: false, e: "O(n\u00b2) \u2014 checks all pairs." },
      { s: "In Closest Pair D&C, you need to check each strip point against all others.", ans: false, e: "Only the next 11 points (sorted by y), thanks to the packing argument." },
      { s: "The Closest Pair combine step runs in O(n) (assuming strip pre-sorted).", ans: true, e: "\u2264 11 comparisons per point = O(n)." },
      { s: "Naive D&C for Closest Pair runs in O(n log n).", ans: false, e: "O(n log\u00b2 n). Pre-sorting needed for O(n log n)." },
      { s: "No two same-side points can share a (\u03b4/2)\u00d7(\u03b4/2) box in the strip.", ans: true, e: "Otherwise their distance would be < \u03b4, contradicting \u03b4." },
      { s: "Closest Pair can be improved from O(n log\u00b2 n) to O(n log n) by maintaining pre-sorted lists.", ans: true, e: "Eliminates re-sorting at each level." },
      { s: "1D Closest Pair can be solved in O(n) without sorting.", ans: false, e: "Need to sort first: O(n log n)." },
      { s: "Integer addition of two n-bit numbers takes O(n).", ans: true, e: "One pass, right to left, with carry." },
      { s: "Naive D&C for integer multiplication improves over O(n\u00b2) brute force.", ans: false, e: "4 recursive mults: T(n) = 4T(n/2) + O(n) = O(n\u00b2)." },
      { s: "Karatsuba uses only 3 recursive multiplications.", ans: true, e: "a\u2081b\u2081, a\u2080b\u2080, and (a\u2081+a\u2080)(b\u2081+b\u2080)." },
      { s: "Karatsuba runs in O(n log n).", ans: false, e: "O(n^1.585). O(n log n) came from Harvey & van der Hoeven in 2019." },
      { s: "Karatsuba's trick is the same as 3-mult complex number multiplication.", ans: true, e: "Both extract the cross term from (a+c)(b+d) \u2212 ab \u2212 cd." },
      { s: "Kolmogorov's \u03a9(n\u00b2) conjecture for multiplication was proven correct.", ans: false, e: "Karatsuba disproved it." },
      { s: "The conjectured lower bound for integer multiplication is \u03a9(n log n).", ans: true, e: "Sch\u00f6nhage & Strassen, 1971." },
      { s: "Brute-force matrix multiplication runs in O(n\u00b2).", ans: false, e: "O(n\u00b3). Each of n\u00b2 entries requires summing n products." },
      { s: "Naive D&C for matrix mult requires 8 recursive multiplications.", ans: true, e: "Four blocks, each needing two half-sized multiplications." },
      { s: "Naive D&C for matrix mult gives O(n\u00b3), same as brute force.", ans: true, e: "8 \u2192 7 is needed for improvement (Strassen)." },
      { s: "Strassen uses 7 recursive matrix multiplications.", ans: true, e: "T(n) = 7T(n/2) + O(n\u00b2) = O(n^2.807)." },
      { s: "Strassen reduces the number of matrix additions.", ans: false, e: "Strassen uses MORE additions (18 vs 4). Savings come from fewer multiplications." },
      { s: "Strassen achieves O(n\u00b2) matrix multiplication.", ans: false, e: "O(n^2.807). O(n\u00b2) is the unachieved ideal." },
      { s: "The current best matrix mult exponent is \u2248 2.37.", ans: true, e: "Via Coppersmith-Winograd / Laser Method refinements." },
      { s: "Matrix multiplication provably cannot be done faster than O(n\u00b2).", ans: false, e: "\u03a9(n\u00b2) is trivially true but it's unknown if exponent can reach 2." },
      { s: "T(n) = T(n/4) + T(3n/4) + O(n) solves to O(n log n).", ans: true, e: "Each level sums to O(n), depth \u0398(log n)." },
      { s: "T(n) = T(\u221an) + T(n\u2212\u221an) + O(n) is O(n log n).", ans: false, e: "Subproblem stays \u2265 n/2 for ~\u221an steps \u2192 \u03a9(n^{3/2})." },
      { s: "Both Karatsuba and Strassen beat brute force by reducing recursive calls by one.", ans: true, e: "4\u21923 and 8\u21927, trading additions for fewer multiplications." },
      { s: "2 subproblems of size n/2 with O(n) combine = O(n log n).", ans: true, e: "T(n) = 2T(n/2) + O(n) = O(n log n)." },
      { s: "2 subproblems of size n/2 with O(n\u00b2) combine = O(n\u00b2).", ans: true, e: "Combine cost dominates (geometric series)." },
      { s: "Finding median of two sorted n-element databases requires \u03a9(n) queries.", ans: false, e: "O(log n) via binary search." },
      { s: "The binary search for median uses 2 queries per step.", ans: true, e: "One from A, one from B, then eliminates smaller side." },
      { s: "Complex (a+bi)(c+di) can be computed with 2 real multiplications.", ans: false, e: "Minimum is 3." },
      { s: "In PS3 P2a, every recursion tree level sums to at most O(n).", ans: true, e: "Subproblems partition the input." },
      { s: "T(n) = T(n/4) + T(3n/4) + O(n) has depth \u0398(log n) because the n/4 branch reaches 1 after log\u2084 n levels.", ans: false, e: "Depth is determined by the LONGEST path (3n/4 branch): log_{4/3}(n) = \u0398(log n)." },
      { s: "For every problem in this module, naive D&C improved over brute force.", ans: false, e: "Integer Mult and Matrix Mult got same asymptotic runtime." },
      { s: "For Closest Pair, the key difficulty was the combine step.", ans: true, e: "Divide/recurse are straightforward; combining in O(n) is the challenge." },
      { s: "Sch\u00f6nhage-Strassen runs in O(n log n log log n) and is based on FFT.", ans: true, e: "1971; fastest for decades until 2019." },
      { s: "In Strassen's, O(n\u00b2) combine is dominated by the 7T(n/2) recursive term.", ans: true, e: "log\u2082 7 \u2248 2.807 > 2, so recursion dominates." },
      { s: "Reducing 8\u21927 (Strassen) gives a bigger improvement than 4\u21923 (Karatsuba).", ans: false, e: "Karatsuba saves ~0.415 in exponent vs Strassen's ~0.193." },
    ],
  },
],
  },
};
